# SPDX-License-Identifier: LGPL-3.0-only
name = "HexToCterm"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
